(define (problem num-cost-renamed-01)
  (:domain num-cost-renamed)
  (:objects l1 l2 l3 - loc)
  (:init (at l1)
         (conn l1 l2)
         (conn l2 l3)
         (= (cost) 0))
  (:goal (at l3))
  (:metric minimize (cost))
)
