(define (problem num-float-div-01)
  (:domain num-float-div)
  (:objects f0 f1 - farm)
  (:init (adj f0 f1)
         (adj f1 f0)
         (= (x f0) 2.5)
         (= (x f1) 1))
  (:goal (>= (x f1) 3))
)
