(define (problem num-metric-negcoef-01)
  (:domain num-metric-negcoef)
  (:objects l1 l2 l3 - loc)
  (:init (at l1)
         (conn l1 l2)
         (conn l2 l3)
         (= (f) 0)
         (= (g l1) -1)
         (= (g l2) -2)
         (= (g l3) 0))
  (:goal (at l3))
  (:metric minimize (f))
)
