(define (problem num-metric-negdelta-01)
  (:domain num-metric-negdelta)
  (:objects l1 l2 l3 - loc)
  (:init (at l1)
         (conn l1 l2)
         (conn l2 l3)
         (= (f) 0))
  (:goal (at l3))
  (:metric minimize (f))
)
