(define (problem num-cost-expr-01)
  (:domain num-cost-expr)
  (:objects l1 l2 l3 - loc)
  (:init (at l1)
         (conn l1 l2)
         (conn l2 l3)
         (= (total-cost) 0)
         (= (g l1) 1)
         (= (g l2) 2)
         (= (g l3) 0))
  (:goal (at l3))
  (:metric minimize (total-cost))
)
