(define (problem p01)
  (:domain cond-eff-simplify)
  (:objects o - item)
  (:init (pre-a o) (pre-b o) (extra o) (eff-conflict o))
  (:goal (and (done o)
              (eff-entailed-atom o)
              (eff-fully-entailed o)
              (eff-conflict o)
              (eff-untouched o))))
