(define (problem num-float-coef-01)
  (:domain num-float-coef)
  (:objects f0 f1 - farm)
  (:init (adj f0 f1)
         (adj f1 f0)
         (= (x f0) 2.5)
         (= (x f1) 1))
  (:goal (>= (+ (* 1.0 (x f0)) (* 1.7 (x f1))) 8.4))
)
