(define (problem num-metric-nonlinear-01)
  (:domain num-metric-nonlinear)
  (:objects l1 l2 l3 - loc)
  (:init (at l1)
         (conn l1 l2)
         (conn l2 l3)
         (= (f1) 0)
         (= (f2) 0))
  (:goal (at l3))
  (:metric minimize (* (f1) (f2)))
)
