(define (problem num-cost-float-01)
  (:domain num-cost-float)
  (:objects l1 l2 l3 - loc)
  (:init (at l1)
         (conn l1 l2)
         (conn l2 l3)
         (= (total-cost) 0))
  (:goal (at l3))
  (:metric minimize (total-cost))
)
