(define (problem num-cost-decrease-01)
  (:domain num-cost-decrease)
  (:objects l1 l2 l3 - loc)
  (:init (at l1)
         (conn l1 l2)
         (conn l2 l3)
         (= (total-cost) 0)
         (= (h l1) -1)
         (= (h l2) -2)
         (= (h l3) 0))
  (:goal (at l3))
  (:metric minimize (total-cost))
)
